# Generated by Django 2.0.1 on 2018-01-25 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_mrn_id', models.CharField(max_length=50)),
                ('patient_id', models.CharField(max_length=50)),
                ('patient_first_name', models.CharField(max_length=500)),
                ('patient_middle_name', models.CharField(max_length=500)),
                ('patient_full_name', models.CharField(max_length=1000)),
                ('patient_dob', models.DateField()),
                ('patient_dod', models.DateField()),
                ('patient_sex', models.CharField(max_length=50)),
                ('patient_address_line_1', models.CharField(max_length=500)),
                ('patient_address_line_2', models.CharField(max_length=500)),
                ('patient_address_city', models.CharField(max_length=500)),
                ('patient_address_state', models.CharField(max_length=500)),
                ('patient_address_country', models.CharField(max_length=500)),
                ('patient_address_zip', models.CharField(max_length=500)),
                ('record_source', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RecordMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_state', models.CharField(choices=[('UNREVIEWED', 'Not Reviewed'), ('ACCEPTED', 'Match accepted but not fixed'), ('FIXED', 'Match accepted and fixed'), ('REJECTED', 'Match rejected')], default='UNREVIEWED', max_length=12)),
                ('record1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r1', to='matcher.PatientRecord')),
                ('record2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r2', to='matcher.PatientRecord')),
            ],
        ),
    ]
