# Generated by Django 2.0.1 on 2018-01-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_address_city',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_address_country',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_address_line_1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_address_line_2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_address_state',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_address_zip',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_dod',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_first_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_full_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_middle_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_mrn_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_sex',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='record_source',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
