# Generated by Django 2.0.1 on 2018-01-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_auto_20180125_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_address_city',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_address_country',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_address_line_1',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_address_line_2',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_address_state',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_address_zip',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_first_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_full_name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_middle_name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_mrn_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient_sex',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='record_source',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
